// <auto-generated />
using System;
using BtcEurMarketDepth.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BtcEurMarketDepth.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MarketDepthDbContext))]
    partial class MarketDepthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BtcEurMarketDepth.Infrastructure.Persistence.Entities.OrderBookSnapshotAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AsksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BestAsk")
                        .HasPrecision(20, 8)
                        .HasColumnType("decimal(20,8)");

                    b.Property<decimal?>("BestBid")
                        .HasPrecision(20, 8)
                        .HasColumnType("decimal(20,8)");

                    b.Property<string>("BidsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "AcquiredAt");

                    b.ToTable("order_book_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
